### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by jankoc** [microtower00/obsidian-ai-images#19]
I did check that I have the correct openAI API key (it works for text generator). Could there be changes on the OpenAI-side which makes this not work?

**Comment by microtower00** [comment]
Hello, I just checked and I don't think there have been server side changes, because it is still working for me.
Could you please check that the API key you are using is working also on the image generator?

**Comment by bwydoogh** [comment]
Had the same issue; I had to restart Obsidian to fix that issue.

**Comment by microtower00** [comment]
Will close since 401 means user is unauthorized by OpenAI. It's still dodgy that it worked only after a restar tho.
