### ISSUE TITLE
Error Status 400

### ISSUE THREAD

**Issue by limex** [microtower00/obsidian-ai-images#7]
Hi, 
it worked once and I got an image back.
But on the second try I get a 

![image](https://user-images.githubusercontent.com/1173039/205870880-358a00ac-8380-4707-925c-d5186126e88f.png)

In https://beta.openai.com/account/usage I see the first successfull request. I have enough budget left.

**Comment by microtower00** [comment]
Hi @limex, I'm glad you took the time to try out my work.

I tried reproducing the issue, but I wasn't able to. When I use the command, the request gets handled properly or so it seems.
If you ever have time, could you reproduce your issue and send me a log or a screenshot of the whole response?
![image](https://user-images.githubusercontent.com/58070348/205939990-b0e1342a-de32-472d-98d2-fa9298ffd97c.png)
You should be able to see under these tabs.
Thank you once again for reporting the issue. This work certainly needs more error handling, as you can see.

**Comment by limex** [comment]
This is strange. Works now multiple times. 
Thanks & case closed :)

**Comment by limex** [comment]
Reopened because it happended again:
![image](https://user-images.githubusercontent.com/1173039/206156890-93a23c6a-3ee0-4140-abeb-28aa2c72c508.png)

![image](https://user-images.githubusercontent.com/1173039/206157177-5ecb428b-c5bc-48cc-8b27-6bd6b028bc8c.png)

![image](https://user-images.githubusercontent.com/1173039/206157034-e8e3a1c7-f5b0-4b7c-9840-e0621ec98fe2.png)

Obviosly "Elon Musk" was the reason. 
Question: Would you consider to show success/error messages in a toast?

**Comment by microtower00** [comment]
Yes, this certainly needs error handling.

**Comment by AMGMNPLK** [comment]
More error 400

![CleanShot 2023-10-14 at 16 30 43@2x](https://github.com/microtower00/obsidian-ai-images/assets/19272675/c7aa62e2-4001-481f-9c7c-9a7850db9a39)
![CleanShot 2023-10-14 at 16 31 07@2x](https://github.com/microtower00/obsidian-ai-images/assets/19272675/b974e697-8639-4d39-be78-62b33d1def5e)
![CleanShot 2023-10-14 at 16 31 15@2x](https://github.com/microtower00/obsidian-ai-images/assets/19272675/93a62cd2-69e5-46fa-b595-35958abba959)

API key tested
![CleanShot 2023-10-14 at 16 33 01@2x](https://github.com/microtower00/obsidian-ai-images/assets/19272675/f76f7acc-c417-4132-884b-f6ce20c6b690)
