### ISSUE TITLE
[Feature] Keep Marked Text after Image Generation

### ISSUE THREAD

**Issue by limex** [microtower00/obsidian-ai-images#8]
**Observed**:
When generating an Image from a Text, the text is replaced by the image.

**Change Request:**
Don't replace/delete the Text, add the image under it.

**User Story:**
As a user I want to see the text AND the image that was generated from it, because I want to learn and improve the generated images.
As a user I want to experiment with different AI models and compare the results.

**Comment by limex** [comment]
Interesting thoughts. 
So: a config for that is definitely appreciated.

**Comment by microtower00** [comment]
I will be adding a setting for this when I have time. I think the setting title will be "**Keep the prompt in the document after the generation**". I'll implement it as a checkbox.
